[build]
  publish = "dist"
  command = "npm run build"
  functions = "netlify/functions"

[dev]
  command = "npm run dev"
  functions = "netlify/functions"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  timeout = 26
