[build]
  base = "Frontend"
  publish = "/dist"
  functions = "netlify/functions"

[dev]
  command = "npm run dev"
  functions = "netlify/functions"
  targetPort = 5173
  port = 8888

[functions."*"]
  timeout = 26

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200