[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  command = "npm run dev"
  functions = "netlify/functions"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

  # Apply to all functions
  [functions."*"]
<<<<<<< HEAD
    timeout = 26
=======
    timeout = 26
>>>>>>> f608752d1b59d3d2249dc738024c9ae4e0e7b690
