[build]
  base = "Frontend"
  publish = "Frontend/dist"
  functions = "Frontend/netlify/functions"

[dev]
  command = "npm run dev"
  functions = "Frontend/netlify/functions"
  targetPort = 5173
  port = 8888

[functions."*"]
  timeout = 26
